<?php
/**
 * Implementation of hook_menu
 */
function lunchnlearn_menu() {
  $items = array();
  
  $items['lunchnlearn/test'] = array(
    'title' => 'Testing Lunch N learn Custom Hooks',
    'page callback' => 'lunchnlearn_test_page',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );
  
  $items['lunchnlearn/test-alter'] = array(
    'title' => 'Testing Drupal Alter',
    'page callback' => 'lunchnlearn_test_alter_page',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );
  
  return $items;
}

/**
 * Page callback for the test page
 */
function lunchnlearn_test_page() {
	module_load_include('inc', 'lunchnlearn', 'includes/lunchnlearn.helpers');
  
  $title = 'title 1';
  $uid = 1;
  $status = 1;
  
  //$record = lunchnlearn_helpers_insert_lunchnlearn_record($title, $status, $uid);
  
	return 'Testing Only';
}

/**
 * Implementation of hook_lunchnlearnrecordapi
 */
function lunchnlearn_lunchnlearnrecordapi(&$record, $op) {
	if ($op == 'presave') {
    drupal_set_message('Presave called');
    $record->title = 'Modified Title';
  }
  
  if ($op == 'insert') {
    drupal_set_message('Insert called');
  }
}

/**
 * Page callback for test alter page
 */
function lunchnlearn_test_alter_page() {
  module_load_include('inc', 'lunchnlearn', 'includes/lunchnlearn.helpers');
	return var_export(lunchnlearn_helpers_build_contrived_array(), 1);
}

/**
 * Implementation of hook_lunchnlearn_contrived_array_alter
 */
function lunchnlearn_lunchnlearn_contrived_array_alter(&$contrived_array) {
	//$contrived_array['afraazs_new_cool_array_index'] = 'foo';
}
